{% set version = "3.5.1" %}

package:
  name: r
  version: {{ version }}

build:
  number: 1000

requirements:
  host:
    - r-base {{ version }}
  run:
    - r-base {{ version }}
    - r-recommended {{ version }}

# test to force the test env creation
# if any dependency is missing the test env creation will fail
test:
  commands:
    - $R -e "library('MASS')"           # [not win]
    - "\"%R%\" -e \"library('MASS')\""  # [win]

about:
  home: http://www.r-project.org/
  license: GPL-3.0
  summary: 'R is a free software environment for statistical computing and graphics.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
