appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: vtVULGC1GMP8/huyfLCEGXwVH1mtJO0950ai7WptYvoBcW0L13ZZRDZD+GtO+drssL1QwWMAx6/zcbSb02sS8cI5tLtlEEHpHn5SOvN6D3vd5uPJ0Neo5WhZEG1Ph7THJgVy2yt5pQDnxPa1wjoTdOIC8LjamQQ5p0xIBaGuTrraAWuJ8bit9o2H+mmK/UgsVbOkH7U+5HVCpG5bVtDbNRJ91ZxYOUczH04JJd4aM57lQDhsQKAFRwS1+KmnTiIRTtBSqAUJ4rt34vhItlWDGwjgISG86u4+A4MARfEVo1xYjwF30Im0bEtD9wO4BunofApzv6wWC3ZCYOO4PhRBFBcvIEowRiXCjcHnpMyTV/hlMAv+laH6Bv78mELSIxTMVrhNApNh4dNnQr1fPA62cMvJl/lZU3HHpFiC65UyB8WKX3UXiIDt+StlS+KKaLrWUJX6BahWbwWvEkahaRdaHPcsDskQpnTE0CceM3dWF9b0KUrCjPOK+fh33EzEo/QAfuYrFm5GfHm1T+lyPs5F6uAMWOvsq1Ho0TgTdEvYY1F8I2vC/XQp6ij+c9ekERfmlT7ld5bIgUbOjvYHFNLvbNhFkc/l9Ob1m/xxLncInsUzMKa1cde+pu90KrNwO39rNp6tpTSTdaxmUcrCoKovdRFnghcp+xyaIHKxhTidjMA=
conda_forge_output_validation: true
